In [2]:
import sys
sys.path.append('..')
import numpy as np
import cupy as cp
import dask.array as da
import jax.numpy as jnp

# ProximableLoss

In [6]:

from pycsou.func.loss import ProximableLoss
from pycsou.func.penalty import L1Norm

for xp in [np, cp]:
    y = xp.arange(10)
    func = L1Norm(dim=y.size)
    loss = ProximableLoss(func=func, data=y)
    x = 2 * xp.arange(10)
    print(xp.allclose(loss(x), func(x-y)))
    # True
    print(xp.allclose(loss.prox(x, tau=1), func.prox(x-y, tau=1) + y))
    # True

True
True
True
True


# DifferentiableLoss

In [7]:
from pycsou.func.loss import DifferentiableLoss
from pycsou.func.penalty import SquaredL2Norm

for xp in [np, cp]:
    y = xp.arange(10)
    func = SquaredL2Norm(dim=y.size)
    loss = DifferentiableLoss(func=func, data=y)
    x = 2 * xp.arange(10)
    print(xp.allclose(loss(x), func(x-y)))
    # True
    print(xp.allclose(loss.gradient(x), 2*(x-y)))
    # True


True
True
True
True


# L2Loss

In [8]:
from pycsou.func.loss import L2Loss
from pycsou.func.penalty import L2Norm

for xp in [np, cp]:
    y = xp.arange(10)
    loss = L2Loss(dim=y.size, data=y)
    func = L2Norm(dim=y.size)
    x = 2 * xp.arange(10)
    print(xp.allclose(loss.prox(x, tau=1), func.prox(x-y, tau=1) + y))
    # True

True
True


# SquaredL2Loss

In [9]:
from pycsou.func.loss import SquaredL2Loss
from pycsou.func.penalty import SquaredL2Norm
from pycsou.linop.base import DenseLinearOperator

for xp in [np, cp]:
    y = np.arange(10)
    loss = SquaredL2Loss(dim=y.size, data=y)
    Gmat = np.arange(100).reshape(10, 10).astype(float)
    G = DenseLinearOperator(Gmat, is_symmetric=False)
    G.compute_lipschitz_cst()
    fwd_loss = loss * G
    x = 2 * np.arange(10)
    print(np.allclose(loss(x), np.linalg.norm(y - x) ** 2))
    # True
    print(np.allclose(fwd_loss(x), loss(G(x))))
    # True
    print(np.allclose(fwd_loss.diff_lipschitz_cst, 2 * (G.lipschitz_cst ** 2)))
    # True
    print(np.allclose(fwd_loss.gradient(x), 2 * G.adjoint(G(x) - y)))
    # True

True
True
True
True
True
True
True
True


# L2BallLoss

In [10]:
from pycsou.func.loss import L2BallLoss
from pycsou.func.penalty import L2Ball

for xp in [np, cp]:
    y = xp.arange(10)
    loss = L2BallLoss(dim=y.size, data=y, radius=2)
    func = L2Ball(dim=y.size, radius=2)
    x = 2 * xp.arange(10)
    print(xp.allclose(loss.prox(x, tau=1), func.prox(x-y, tau=1) + y))
    # True

True
True


# L1Loss

In [12]:
from pycsou.func.loss import L1Loss
from pycsou.func.penalty import L1Norm

for xp in [np, cp]:
    y = np.arange(10)
    loss = L1Loss(dim=y.size, data=y)
    func = L1Norm(dim=y.size)
    x = 2 * np.arange(10)
    print(np.allclose(loss.prox(x, tau=1), func.prox(x-y, tau=1) + y))
    # True

True
True


# SquaredL1Loss

In [13]:
from pycsou.func.loss import SquaredL1Loss
from pycsou.func.penalty import SquaredL1Norm

for xp in [np, xp]:
    y = xp.arange(10)
    loss = SquaredL1Loss(dim=y.size, data=y)
    func = SquaredL1Norm(dim=y.size)
    x = 2 * xp.arange(10)
    print(xp.allclose(loss.prox(x, tau=1), func.prox(x-y, tau=1) + y))
    # True

True
True


# L1BallLoss

In [15]:
from pycsou.func.loss import L1BallLoss
from pycsou.func.penalty import L1Ball

for xp in [np, cp]:
    y = xp.arange(10)
    loss = L1BallLoss(dim=y.size, data=y, radius=2)
    func = L1Ball(dim=y.size, radius=2)
    x = 2 * xp.arange(10)
    print(xp.allclose(loss.prox(x, tau=1), func.prox(x-y, tau=1) + y))
    # True

True
True


# LInftyLoss

In [16]:
from pycsou.func.loss import LInftyLoss
from pycsou.func.penalty import LInftyNorm

for xp in [np, cp]:
    y = np.arange(10)
    loss = LInftyLoss(dim=y.size, data=y)
    func = LInftyNorm(dim=y.size)
    x = 2 * np.arange(10)
    loss(x)
    # 9
    print(np.allclose(loss.prox(x, tau=1), func.prox(x-y, tau=1) + y))
    # True

True
True


# LInftyBallLoss

In [18]:
from pycsou.func.loss import LInftyBallLoss
from pycsou.func.penalty import LInftyBall

for xp in [np, cp]:
    y = xp.arange(10)
    loss = LInftyBallLoss(dim=y.size, data=y, radius=2)
    func = LInftyBall(dim=y.size, radius=2)
    x = 2 * xp.arange(10)
    print(xp.allclose(loss.prox(x, tau=1), func.prox(x-y, tau=1) + y))
    # True

True
True


# ConsistencyLoss

In [19]:
from pycsou.func.loss import ConsistencyLoss

for xp in [np, cp]:
    y = xp.arange(10)
    loss = ConsistencyLoss(dim=y.size, data=y)
    x = 2 * xp.arange(10)
    loss(x), loss(y)
    # (inf, 0)
    print(xp.allclose(loss.prox(x, tau=1), y))
    # True

True
True


# KLDivergence

In [21]:
from pycsou.func.loss import KLDivergence

for xp in [np, cp]:
    y = xp.arange(10)
    loss = KLDivergence(dim=y.size, data=y)
    x = 2 * xp.arange(10)
    print(loss(x))
    # 13.80837687480246
    print(xp.round(loss.prox(x, tau=1)), type(xp.round(loss.prox(x, tau=1))))
    # array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

13.80837687480246
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.] <class 'numpy.ndarray'>
13.80837687480246
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.] <class 'cupy._core.core.ndarray'>
